### ISSUE TITLE
Vangst Marketing Site issues:

### ISSUE THREAD

**Issue by Carmer** [vangst/planning#4]
After doing a pass through the marketing pages, I noticed a few varying content issues...

## Tasks

- [ ] The `h1` content is the same on [the about page](https://vangst.com/about) as the [company guide page](https://vangst.com/companies/guide)
- [ ] The `h1` content and hero content is the same on [the blog page](https://vangst.com/blog) as the [reports page](https://vangst.com/reports)
- [ ] Content is duplicated between the [home page](https://vangst.com/), [about us](https://vangst.com/about), [testimonials](https://vangst.com/about/testimonials), [help](https://vangst.com/help) and even a few modules on the [member](https://vangst.com/members/guide)/[company](https://vangst.com/companies/guide) guide pages. In lots of cases, only the headline, hero image and module order is what has changed. Can we either produce content targeted specifically for these pages or condense the number of pages down to maybe 1-3 pages?
- [ ] Most marketing pages have CTAs in the header to the "About Us" page. Viewers on the [member](https://vangst.com/members/guide) and [company](https://vangst.com/companies/guide) guide pages might benefit from a CTA that lead to account creation. Perhaps a CTA in the header isn't needed though since it's before the viewer has seen any page content?
- [ ] With the [new "Show our Services" being shaped](https://coda.io/d/2023-Shaping_dc7scXPTWgD/Any-customer-posting-a-job-knows-the-services-we-offer_suLpL#_luZkI), will we still need the [job booster page](https://vangst.com/jobs/job-booster)? And if it stays around, can we turn that image into a design for crawlable content?
- [ ] While most sections make sense for logged in vs logged out users, some sections content could be more tailored to their authentication status. These mainly occur in the footer and CTAs around signing up for an account.
- [ ] There is probably quite a bit SEO juice to be had on the [help/faq page](https://vangst.com/help). Can we blow this out with internal links to all aspects of the site? Explain our concepts like training, connecting with users, finding jobs and just using the product in general?

---

_:wave:!.. The UI updates to the pages on vangst.com can be [seen on this preview app](https://web-git-mkitt-fix-things-vangst.vercel.app). They will be deployed to UAT after code review._
